### ISSUE TITLE
Advanced Properties

### ISSUE THREAD

**Issue by vexx32** [MikeShepard/WPFBot3000#135]
Is there a way that you can allow for things like specifying exact positions of items in a dialogue window in a similar manner to the way you can with XAML? 

Could you include an additional sub function for each item, or an additional parameter that takes, for examples sake, a hashtable?

This could be used to generate XAML in order to put together a more effective form and allow users to actually add some visual styling to the form, rather than just having to rely on however it happens to end up looking.

**Comment by MikeShepard** [comment]
Each control function has a -property parameter which takes a hashtable for
setting properties.

Is that what you're looking for?

In other news, I'm working on creating styles, too.
